### PR TITLE
fix(server): fix relative path of dist

### PR DESCRIPTION
**Pull request by Char2sGu**
### Summary of changes

Fix the relative path of dist when `process.env.DIST` is not specified.

### Relinquishment of Rights

Please mark following checbkox to confirm that you relinquish all rights of your changes, including code, text, and other copyrighted material.

- [x] I waive and relinquish all rights regarding this changes including code, text, and images to Deepkit UG (limited). This changes including code, text, and images, are under MIT license without attribution requirement.

### CODE REVIEW

**Comment by marcj** [comment]
Mh, the current version works fine and is actually deployed. What error did you get?

**Comment by Char2sGu** [comment]
```sh
char2s@REDMI-G:~/projects/deepkit-website$ npm run server:watch

> @deepkit/website@0.0.0 server:watch
> ts-node-dev --project ./src/server/tsconfig.json ./src/server/app.ts server:start

[INFO] 23:59:56 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.6.2)
2022-03-31T15:59:58.780Z [LOG] Start server ...
2022-03-31T15:59:58.789Z [LOG] Migrate database MongoDatabase default (MongoDatabaseAdapter)
2022-03-31T15:59:58.801Z [LOG] RPC Controller FrameworkController framework
2022-03-31T15:59:58.802Z [LOG] 3 HTTP routes
2022-03-31T15:59:58.802Z [LOG] HTTP Controller FrameworkHttpController
2022-03-31T15:59:58.802Z [LOG]   GET /benchmarks
2022-03-31T15:59:58.802Z [LOG]   POST /benchmark/add
2022-03-31T15:59:58.802Z [LOG]   GET /benchmark
2022-03-31T15:59:58.802Z [LOG] HTTP listening at http://127.0.0.1:8080
2022-03-31T15:59:58.802Z [LOG] Server started.
2022-03-31T16:00:52.735Z [ERROR] HTTP kernel request failed Error: ENOENT: no such file or directory, open '/home/char2s/projects/dist/browser/index.html'
    at Object.openSync (node:fs:585:3)
    at readFileSync (node:fs:453:35)
    at new AngularUniversalListener (/home/char2s/projects/deepkit-website/node_modules/@deepkit/angular-universal/src/listener.ts:38:38)
    at Injector.eval [as resolver] (eval at raw (/home/char2s/projects/deepkit-website/node_modules/@deepkit/core/src/compiler.ts:77:16), <anonymous>:21:42)
    at Injector.get (/home/char2s/projects/deepkit-website/node_modules/@deepkit/injector/src/injector.ts:246:21)
    at InjectorContext.get (/home/char2s/projects/deepkit-website/node_modules/@deepkit/injector/src/injector.ts:865:29)
    at self (eval at buildAsync (/home/char2s/projects/deepkit-website/node_modules/@deepkit/core/src/compiler.ts:111:20), <anonymous>:73:87)
    at HttpKernel.handleRequest (/home/char2s/projects/deepkit-website/node_modules/@deepkit/http/src/kernel.ts:42:17) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/char2s/projects/dist/browser/index.html'
}
^C2022-03-31T16:03:22.610Z [WARNING] Received SIGINT. Stopping server ...
```

**Comment by Char2sGu** [comment]
Hi @marcj. It shows the error above. And I do found that the relative path's target is outside the project root.

**Comment by marcj** [comment]
Mh it might be that `dirname(getCurrentFileName()` returns the wrong path. could you check what it returns?

**Comment by Char2sGu** [comment]
It is `/home/char2s/projects/deepkit-website/src/server`, which I think is an expected value?

**Comment by marcj** [comment]
actually, I'm using locally 

```
npm run server:build
npm run server:run
```

which lets `getCurrentFileName` return a different folder from dist which is the one that works with the current code. this would break if we apply this PR.

following works for both `server:run` and `server:watch`: 

```
(process.env.DIST || findParentPath('/dist', dirname(getCurrentFileName()))) + '/browser'
```

**Comment by Char2sGu** [comment]
Hi @marcj. Is there a formatter/linter specified in this repo? My formatter seems to be incompatible with the code, and the `lint` script in `package.json` shows that there haven't been a linter installed yet.

**Comment by marcj** [comment]
No linter yet, as the well-known ones break the fluid decorator API (they wrap it in (), like `@(http.GET('/'))`) and have usually ugly rules, for which I haven't found the time to tune the linter config yet.

**Comment by Char2sGu** [comment]
> actually, I'm using locally
> 
> ```
> npm run server:build
> npm run server:run
> ```
> 
> which lets `getCurrentFileName` return a different folder from dist which is the one that works with the current code. this would break if we apply this PR.
> 
> following works for both `server:run` and `server:watch`:
> 
> ```
> (process.env.DIST || findParentPath('/dist', dirname(getCurrentFileName()))) + '/browser'
> ```

Or just `path.join(process.cwd(), "dist")`?

**Comment by Char2sGu** [comment]
> No linter yet, as the well-known ones break the fluid decorator API (they wrap it in (), like `@(http.GET('/'))`) and have usually ugly rules, for which I haven't found the time to tune the linter config yet.

Oh I didn't met such problems with Prettier.

The only problem is:
```ts
[
  MongoDatabase,
],
```

will be mandatorily formatted to

```ts
[MongoDatabase],
```

unless the line is too long or there is a comment as a suffix of an item.

```ts
[
  MongoDatabase, //
],
```

But I guess it brings more benefits.

**Comment by marcj** [comment]
would work as well, yes. I would go with findParentPath from deepkit/core though so its a bit more flexible

**Comment by Char2sGu** [comment]
Modified @marcj

**Comment by Char2sGu** [comment]
okay.. seems fixed

**Pull request closed without merging**
