### PR TITLE
Fix typo in "Functional schema" section

### PR DESCRIPTION
**Pull request by jonahsnider**
### Summary of changes

Fixes a small capitalization error in the "Functional schema" of the ORM page.

### Relinquishment of Rights

Please mark following checbkox to confirm that you relinquish all rights of your changes, including code, text, and other copyrighted material.

- [x] I waive and relinquish all rights regarding this changes including code, text, and images to Deepkit UG (limited). This changes including code, text, and images, are under MIT license without attribution requirement.

### CODE REVIEW

**Comment by marcj** [comment]
`user` is actually a variable (not a class), which are usually lowercase :)

**Comment by jonahsnider** [comment]
Then there's still an error in the snippet as `const user = ...` is declared twice, unless that's intentional.

Also, isn't the point of this to show different ways of declaring schemas? Instead of limiting your naming style because of JavaScript convention why not make your own and say "schemas names should use upper camelcase".

**Comment by marcj** [comment]
Oh, you are right. This wasn't intentional. Thanks! I'm going to fix that.

Yeah, we could introduce a new style, but I prefer to not tell people how they should write variable names, especially when they are not classes. "t.schema" creates an object instance of "ClassSchema", which acts as a regular object, so having it lowercase feels natural to me.

**Comment by marcj** [comment]
Closing since this is outdated and does not exist anymore

**Pull request closed without merging**
